

Table organisations {
    id int [pk, not null]
    name varchar(255) [not null]
}

Table sectors {
    id int [pk, not null]
    name varchar(255) [not null]
    organisation_id int [not null, ref: > organisations.id]
}

Table products {
    id int [pk, not null]
    name varchar(255) [not null]
    description varchar(255) [not null]
}

Table product_sectors {
    product_id int [not null, ref: > products.id]
    sector_id int [not null, ref: > sectors.id]
}
